# Generated by Django 4.1.4 on 2022-12-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='url_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
