# Generated by Django 4.1.4 on 2022-12-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
